### ISSUE TITLE
New stable release compatible with symfony 3

### ISSUE THREAD

**Issue by kYem** [braincrafted/bootstrap-bundle#420] opened 2016-01-22 13:16 UTC
Is there a plan to release a new stable version soon that will be compatible with symfony 3? Is there any blockers?

At the moment I had to switch from dev-master to dev-develop to get all deprecation fixes, obviously not ideal.

**Comment by dkisselev** [comment] 2016-01-22 17:15
This issue is technically a duplicate of numerous other ones, and a release is planned whenever Florian has a chance to sit down and do it, but he's been busy and hasn't been able to sit down and tag an actual release.

Have you seen any deprecation notices in your app on dev-master? The project doesn't have 100% test coverage so it's been coming down to users reporting deprecations to catch all the edge cases.

**Comment by florianeckerstorfer** [comment] 2016-01-23 17:24
Ok, so I am preparing the release right now. If the Travis CI tests go through successfully the new version will released today.

**Comment by kYem** [comment] 2016-01-23 18:05
Great news.

@dkisselev `dev-master` is really behind, so there were some deprecations, but since switching to `dev-develop` I did not spot any

**Comment by florianeckerstorfer** [comment] 2016-01-23 18:09
Yeah, this should be done. Finally.

**Comment by florianeckerstorfer** [comment] 2016-01-23 18:11
I am currently trying to fix the documentation. I made some progress, but will not be able to finish it today. If someone has time this weekend it would be great if you could help.

**Closed by florianeckerstorfer** 2016-01-23 18:11 UTC
